### ISSUE TITLE
Messages are not sending

### ISSUE THREAD

**Issue by dpaola2** [Bloc/Messenger#31]
I suspect an authentication issue, or that we're not passing the correct parameters (or enough of them) when sending a message. 

See https://rollbar.com/bloc/Bloc/items/25668/?item_page=0&#instances for errors on the server side of the platform.

**Comment by bdougie** [comment]
This is also affecting logging in as well. @ajalger ran into this yesterday

**Comment by ajalger** [comment]
@bdougie When you solve the issue of not being able to log in, please let me know. I can't get past the login page.

**Comment by ajalger** [comment]
This should now be fixed in PR #47
