### ISSUE TITLE
Better Error Message on Login Component

### ISSUE THREAD

**Issue by bdougie** [Bloc/Messenger#8]
<img width="441" alt="screenshot 2016-04-01 22 30 43" src="https://cloud.githubusercontent.com/assets/5713670/14224675/82f724d2-f859-11e5-8f11-c03634d1f559.png">

ActivityIndicatorIOS also needs to be moved to ios.index.js

**Comment by dpaola2** [comment]
Putting up a PR shortly -- but we should update https://www.bloc.io/apidoc/1.0/sessions/create.html to return a more useful error message in the event of a 404 (which in this case means username not found).
